identifier: Paymentservice
title: Paymentservice
team: 
  - service_team
blueprint: service
properties:
  workload_short: scim
  language: python
  deployment_zone: private
  net_version: net8.3
  readme: file://./README.md
  relations:
  calcserv: priya_calculation_service
