identifier: Paymentservice
title: Paymentservice
team: 
  - service_team
blueprint: service
properties:
  workload_short: scim
  language: python
  deployment_zone: private
  net_version: net8.0
   readme: file://README.md
   relations:
  calcserv: core_process_service
  ci_version: templates-apps-ci-cd-0.1.87
